export interface DockerComposeConfig {
  instanceId: string;
  n8nVersion: string;
  projectName: string;
  size?: string;
  n8nPort?: string;
  postgresPassword?: string;
  environment?: Record<string, string>;
}

const DOCKER_SIZE_LIMITS: Record<string, { cpus: string; memory: string }> = {
  SMALL:  { cpus: '0.5', memory: '1024M' },
  MEDIUM: { cpus: '1.0', memory: '2048M' },
  LARGE:  { cpus: '2.0', memory: '4096M' },
  XLARGE: { cpus: '4.0', memory: '8192M' },
};

export function generateComposeFile(config: DockerComposeConfig): string {
  const {
    n8nVersion,
    size = 'SMALL',
    n8nPort = '0',
    postgresPassword = 'n8n_local',
    environment = {},
  } = config;

  const limits = DOCKER_SIZE_LIMITS[size.toUpperCase()] || DOCKER_SIZE_LIMITS.SMALL;

  const extraEnvLines = Object.entries(environment)
    .map(([key, value]) => `      - ${key}=${value}`)
    .join('\n');

  const extraEnvBlock = extraEnvLines ? `\n${extraEnvLines}` : '';

  return `# Auto-generated by n8n-hosting-app local Docker provisioner
# Instance: ${config.instanceId}
services:
  n8n:
    image: n8nio/n8n:${n8nVersion}
    ports:
      - "${n8nPort}:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=${postgresPassword}
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=UTC${extraEnvBlock}
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - n8n_data:/home/node/.n8n
    deploy:
      resources:
        limits:
          cpus: '${limits.cpus}'
          memory: ${limits.memory}
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:5678/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 12
      start_period: 30s

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=n8n
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=${postgresPassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 10s
    restart: unless-stopped

volumes:
  n8n_data:
  postgres_data:
`;
}
